### PR TITLE
Implemented Service Endpoint Registration using Source Generation

### PR DESCRIPTION
**Pull request by iamadamreed**
This is an example of implementing a Source Generated Service Endpoint helper for registering endpoints using Attributes.

See the example project in `tests/EndpointRegistrationTest`

Usage:
```
await using var nats = new NatsConnection();
var svc = new NatsSvcContext(nats);
await svc.AddEndpointControllers();
```

Declarations:
```
[NatsServiceController(Name = "Name", Version = "Version", QueueGroup = "QueueGroup")]
public class PingController : NatsServiceControllerBase
{
    [NatsServiceEndpoint("Ping", "Subject", "QueueGroup")]
    public async ValueTask Ping(NatsSvcMsg<string> arg)
    {
        if (arg.Data == "Ping!")
            await arg.ReplyAsync("Pong!");
    }
}
```

### CODE REVIEW

**Comment by adamreed90** [comment]
Still working at this, updated my example, some issues I've had so far are that Attributes can't support the use of Metadata and Serializer configuration as those types aren't supported in attributes.

**Comment by srs-adamr** [comment]
@rickdotnet Have a look at this, something I'm working on.

**Comment by adamreed90** [comment]
@rickdotnet Have a look at this, something I'm working on.

**Comment by adamreed90** [comment]
Hoping to get back to work on this at the end of the month, had some things come up.

**Comment by srs-adamr** [comment]
@mtmk You can go ahead and close this, I don't think I'll be taking this direction anymore.

**Pull request closed without merging**
