### PR TITLE
Nats web socket opts improvements

### PR DESCRIPTION
**Pull request by Ivandemidov00**
Resolves [#610](https://github.com/nats-io/nats.net/issues/610)

### CODE REVIEW

**Comment by Ivandemidov00** [comment]
@caleblloyd can you take look? Did I interpret all the ideas you had in mind correctly?

**Comment by caleblloyd** [comment]
I will try to take a look tomorrow!

**Comment by caleblloyd** [comment]
Here are some un-tested recommendations based on your PR: https://github.com/nats-io/nats.net/commit/4da55d4b018a28d84f5f0f84b9d59a0ecd876838

Feel free to cherry-pick that commit into this branch if you think it looks good.  The 2 main things left to do:

- Make sure adding TLS Options / Request Headers is ignored on Blazor and does not throw
- Add tests for TLS Options ClientCertificates / RemoteCertificateValidationCallback over WebSockets

**Comment by Ivandemidov00** [comment]
> Here are some un-tested recommendations based on your PR: [4da55d4](https://github.com/nats-io/nats.net/commit/4da55d4b018a28d84f5f0f84b9d59a0ecd876838)
> 
> Feel free to cherry-pick that commit into this branch if you think it looks good. The 2 main things left to do:
> 
>     * Make sure adding TLS Options / Request Headers is ignored on Blazor and does not throw
> 
>     * Add tests for TLS Options ClientCertificates / RemoteCertificateValidationCallback over WebSockets

Thanks, I'll run some tests

**Comment by Ivandemidov00** [comment]
@caleblloyd I checked when adding headers to Blazor, an error appears.
And I have my doubts, what kind of behavior would we like to see?
 - Connect the client at any cost, without adding headers when it's Blazor
 - Throwing the PlatformNotSupportedException error that was received while adding headers to the Blazor wss client connection

**Comment by caleblloyd** [comment]
It’s more the TLS options I was worried about but maybe it is ok to throw there too? I don’t know how common it is for someone to configure an Isomorphic client for Blazor and .NET projects.

**Comment by caleblloyd** [comment]
I think we don't need detect or ignore Blazor right now, since Headers would need to be explicitly added.  I changed the TLS check to look for TLS Certs being explicitly added.  Also added some tests for WebSocketSecure

**Review by caleblloyd — APPROVED** [review]
Approved, @mtmk can you take a quick look and merge if you're happy?

**Comment by Ivandemidov00** [comment]
@caleblloyd Thanks for help :)

**Review by mtmk — APPROVED** [review]
LGTM thank you @caleblloyd and @Ivandemidov00 💯

**Pull request merged**
